# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8677a8af010ea2ab1cb8814a27e328539f8f8b0b94b545c8ab8a5206172536b52043d4865e243e75064699c2db1fb56aef52b3967f7876609f99d5da30c046c6

test:
  secret_key_base: 5d6f628cce1af48910a4a09aeab67dac180d0c7209fd4a3b0477ae35d2b3071159b26b87c67d181e1c3696603aa3c9009f11f25f298c3342b07534433f4c28f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
